#!/bin/bash
#--DEFINIR CONEXIONES Y RUTAS--
DB_SERVER='mysql.bloomweb.co'
DB_DATABASE='bloomweb_ez2'
DUMP_PATH='../dump.sql'
SSH_CONN_STRING='embalao@bloomweb.co'
PATH_TO_IMAGES='/home/embalao/ez2.bloomweb.co/app/webroot/img/uploads'
PATH_TO_DOWNLOAD='../../app/webroot/img/'
#--DEFINIR EL SCRIPT--
clear
ssh embalao@bloomweb.co -L 13306:${DB_SERVER}:3306 -N &
echo "--------------------------------------------------"
echo "Esperando que se cree el tunel mediante SSH..."
echo "--------------------------------------------------"
sleep 10
echo "--------------------------------------------------"
echo "Iniciando dump SQL..."
echo "--------------------------------------------------"
mysqldump -u bloomweb -prr40r900343 -h 127.0.0.1 --port=13306 ${DB_DATABASE} > ${DUMP_PATH}
echo "----------------------------------------------"
echo "Finalizado el dump SQL..."
echo "Terminar el proceso ssh..."
echo "Se cerrarán TODAS las conexiones SSH..."
echo "----------------------------------------------"
sleep 2
killall ssh
echo "--------------------------------------------------"
echo "Cerradas las conexiones SSH..."
echo "Ingresar los datos a la BD local..."
echo "--------------------------------------------------"
mysql -u bloomweb -prr40r900343 ${DB_DATABASE} < ${DUMP_PATH}
sleep 2
echo "--------------------------------------------------"
echo "Los datos se debieron de haber ingresado."
echo "En caso de error revisar que la BD destino exista."
echo "--------------------------------------------------"
echo "--------------------------------------------------"
echo "Descargando imagenes desde el servidor..."
echo "--------------------------------------------------"
scp -r ${SSH_CONN_STRING}:${PATH_TO_IMAGES} ${PATH_TO_DOWNLOAD}
sleep 2
echo "--------------------------------------------------"
echo "Terimanada descarga de imagenes."
echo "--------------------------------------------------"
